### ISSUE TITLE
CRAN policy violation

### ISSUE THREAD

**Issue by thomascwells** [shanejorr/usincometaxes#4]
Current text of the `usincometaxes` package on CRAN quoted below. 

Do you know what lead to the policy violation? Is there anything I can do to help? 

> Package ‘usincometaxes’ was removed from the CRAN repository.
> 
> Formerly available versions can be obtained from the [archive](https://cran.r-project.org/src/contrib/Archive/usincometaxes).
> 
> Archived on 2022-05-13 for policy violation.
> 
> A summary of the most recent check results can be obtained from the [check results archive](https://cran-archive.r-project.org/web/checks/2022/2022-05-12_check_results_usincometaxes.html).
> 
> Please use the canonical form https://cran.r-project.org/package=usincometaxes to link to this page.

**Comment by shanejorr** [comment]
Here is the message in its entirety:

> Dear maintainer,
> 
> Apparently checking this modifies the user's ~/.ssh/known_hosts, in
> violation of the CRAN Policy's
>
>   Packages should not write in the user’s home filespace (including
>   clipboards), nor anywhere else on the file system apart from the R
>   session’s temporary directory ...
>
> We thus have to archive your package for policy violation.
>
> Please allow yourself some time for carefully studying the Policy and
> verifying that your package indeed complies with it before possibly
> resubmitting.

I checked it on my machine and the package does write to the .ssh/known_hosts file due to the ssh command used to send and retrieve the data from the TAXSIM server. It adds the host name as a known host. It does this for security reason. You can actually see this on your own machine. If you use the package and then go to your machine's .ssh/known_hosts file, you will see that 'taxsimssh.nber.org' has been added.

I found [this thread](https://superuser.com/questions/141344/dont-add-hostkey-to-known-hosts-for-ssh) that might solve the issue. But, I worry I will inadvertedly bring in security issues. It is something I was going to look into more on the security front.

Off the top of my head, I wonder if I could create a temporary known_hosts file in R's temporary directory and then refer to this file with the parameter `UserKnownHostsFile` in the ssh command?

**Comment by thomascwells** [comment]
I'll spend a little time tomorrow looking at the current state of things so I can at least provide some useful comments!

Also, FWIW, I have a patch in progress for a bug with the col name checking function for the input data frame. I'll create a separate issue and PR for that, but just a heads up.

**Comment by shanejorr** [comment]
I am fixing the issue where ssh writes out to the known_hosts file on branch [update-ssh](https://github.com/shanejorr/usincometaxes/tree/update-ssh). I am creating a kown_hosts file in the temporary directory and writing out to it.

**Comment by thomascwells** [comment]
I was looking into using the `curl` approach described under the html section, here http://taxsim.nber.org/taxsim35/low-level-remote.html. 

I got it to return values, but I'm pretty sure the values are different than any of the other approaches (using the same input data). I don't know what's going on with that!

Have you looked into embedding the web assembly file in the R package? I don't know where to even start with that, but it seems like it would be more robust to potential changes with the API and would (hopefully) be faster than roundtrip SSH.

I think this page is using the embedded .wasm file and it's really nice: https://taxsim.app/

**Comment by shanejorr** [comment]
Regarding using http or ftp, I did not originally using them for the following reasons:

- Daniel suggested SSH. I don't remember the reason, however.
- I cannot get FTP to return results with TAXSIM 35 and http kept giving me an error line on the bottom line.
- My original reading of the [CRAN policies](https://cran.r-project.org/web/packages/policies.html) was that all uplaods and downloads should occur through secure channels: "Downloads of additional software or data as part of package installation or startup should only use secure download mechanisms (e.g., ‘https’ or ‘ftps’). For downloads of more than a few MB, ensure that a sufficiently large timeout is set." Upon rereading, however, I see that this only applies to installation or startup. My first version with TAXSIM 32 allowed users to choose ssh, http, or ftp by using a parameter in the main function. I was able to get http and ftp to work with TAXSIM 32. This would be worth revisiting given my rereading of CRAN requirements, assuming http and / or ftp work correctly.  

Thanks for pointing out taxsim.app, as I had not seen that before. It looks neat and it is certianly intriguing to have the R package itself do the calcualtions. But I would have no idea how to do that either.

**Comment by thomascwells** [comment]
After much head-banging, I got the `curl`+`https` method to work! The biggest gotcha was that the uploaded file cannot have a newline character at the end of the last line. This is very non-standard, but it breaks otherwise. 

Here's some proof of concept code. If you like the way this looks, I can create a branch so we can iterate on it. 

```r
input_df <- data.frame(
  taxsimid  = c(1,2),
  mstat     = c(1,2),
  idtl      = 0, # output details level must be 0 or 2
  year      = 2022,
  state     = 6,
  page      = 0,
  pwages    = c(50000, 100000))

tmp_raw_file <- tempfile()

input_df %>% 
  # convert data frame to string
  readr::format_csv() %>% 
  # remove end-of-line markers for last line only
  sub(x = ., "(\r\n|\n)$", "") %>%
  # write string to temp file
  cat(file = tmp_raw_file)

output_df <- httr::POST(
  url = "https://taxsim.nber.org/uptest/webfile.cgi",
  body = list(txpydata.raw = httr::upload_file(tmp_raw_file))
  ) %>% 
  httr::content(as = 'text') %>%
  readr::read_csv(show_col_types = F)

output_df
```
```
# A tibble: 2 x 10
  taxsimid  year state fiitax siitax  fica frate srate ficar tfica
     <dbl> <dbl> <dbl>  <dbl>  <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
1        1  2022     6  4240.  1618.  7650    12  4.53  15.3  3825
2        2  2022     6  8481   3222. 15300    12  4.53  15.3  7650
```

**Comment by shanejorr** [comment]
That looks good! And in hindsight, the new line character was what was throwing me off. It's why I kept getting an error saying that it expected x number of lines, but only returned y number.

I think it would be great to add this functionality. I envision a single parameter with `taxsim_calculate_taxes()` that allows users to select the upload method (ssh or https), along with a default. At least, that's how I had it in my first iteration on TAXSIM 32, when I got everything to work.

My only suggestion would be to see if you can use vroom instead of readr. I'm currently doing the improting and exporting with vroom because my understanding is that it is a bit faster for large data sets. So, continuing with vroom will simply mean that is one less package to import. I believe `vroom::vroom_format()` should work the same as format_csv.

Also, as of now, I have avoided importing thetidyverse or any of its packages (including magrittr). But, the more functionality I add, the harder it gets to avoid importing more packages!

But, I would be OK with using the new base R pipes. That way we avoid impporting another package and Hadley Wickham is now recommending the base R pipe, [section 5.2 of the updated R for Data Science book](https://r4ds.hadley.nz/workflow-pipes.html), so that works for me!

**Comment by shanejorr** [comment]
Also, I resubmitted the package to CRAN this past weekend after fixing the issue. It was accepted on Monday and has yet to be kicked-back. Last time, it was kicked-back after one day, so I think we might be good on CRAN. But the https functionality would help a lot since some people might have issues with ssh.

**Comment by thomascwells** [comment]
Oh, I forgot to mention another gotcha in the `curl` method. There is a typo on the NBER website for the curl example. [Here](http://taxsim.nber.org/taxsim35/low-level-remote.html), they say the curl code should look like: 

`curl -F txpydata.raw=@txpydata.raw "https://wwwdev.nber.org/uptest/webfile.cgi"`

But I think it should actually be: 

`curl -F txpydata.raw=@txpydata.raw "https://www.taxsim.nber.org/uptest/webfile.cgi"`

I'll take a shot at updating `taxsim_calculate_taxes()` to include a method selection option and submit a PR. I'll do my best to avoid any extra package dependencies.

One thing to consider with the base pipes: I think those would prevent people with older versions of R from using the package. Only really important in the near-term. And regardless, should be easy to keep pipes out of this function. It's pretty simple.

**Comment by shanejorr** [comment]
Thanks! I get the concern with base pipes, so keeping them out may be the best for now. Regarding dependencies, we would cerainly need `httr` for https, so that is totally understandable. Using the package would probably be a safer approach than doing what is done for ssh (creating the command using `shell()` or `system()`).  Thanks again!

I'm going to close this issue.
